### ISSUE TITLE
protected abstract method gets removed

### ISSUE THREAD

**Issue by szepeviktor** [php-stubs/woocommerce-stubs#20]
`WC_Item_Totals  protected abstract function get_values_for_total($field);`

then
```
Class WC_Cart_Totals contains 1 abstract method and must therefore be declared abstract
 or implement the remaining methods (WC_Cart_Totals::get_values_for_total)
 in /home/travis/build/php-stubs/woocommerce-stubs/woocommerce-stubs.php on line 15012
```

@herndlm Please help.

**Comment by szepeviktor** [comment]
Maybe we should simply not remove protected abstract methods.

**Comment by herndlm** [comment]
AFAIK protected methods should only be removed if the class is final, I'll check it out.
but in which context did this error occur? what is executing the stubs?

**Comment by herndlm** [comment]
interesting, there's even a test that makes sure that protected abstract methods stay: https://github.com/php-stubs/generator/blob/v0.8.3/test/files/classes.out.php#L25

**Comment by szepeviktor** [comment]
> what is executing the stubs?

CI
https://github.com/php-stubs/woocommerce-stubs/blob/446c335118632e00854b9ada74319b200e5c78a2/.travis.yml#L39

**Comment by szepeviktor** [comment]
If you extend WC classes stubs must be executed as stubs are for changing docblocks, not for defining classes and methods.

**Comment by herndlm** [comment]
I was also looking in the same direction I think. real stubs only provide docblocks and should normally not be executed, but in the wordpress extension we do execute them to define classes and methods I believe.

See https://phpstan.org/user-guide/stub-files and https://phpstan.org/config-reference#bootstrap

I was just looking into this in the extension a bit, but too many tests start failing if I thinker with it because PHPStan doesn't know e.g. `wp_get_theme()` anymore.

But this might be a different thing, although still related I suppose. The best thing would be to get rid of the stub execution, the second best thing might be to include everything in the stubs still if we have to execute them :/

**Comment by herndlm** [comment]
> It’s like source code, but PHPStan only reads PHPDocs from it. So the namespace and class/interface/trait/method/function names must match with the original source you’re describing. 

basically the "problem" is that we need the original source too and we don't have it, except people properly require e.g. `composer require johnpbloch/wordpress` and configure phpstan to scan that as well. most likely the wordpress "stubs" should then still keep all symbols for now I suppose and we keep executing our "stubs" via the bootstrap config, except you want to change how the extension works / is configured, but I guess this is too annoying for the users.

**Comment by szepeviktor** [comment]
> The best thing would be

Please star my new project: https://github.com/szepeviktor/WordPress-the-good-parts

**Comment by tlewap** [comment]
Same problem here after upgrading to newest phpstan version

**Comment by szepeviktor** [comment]
@herndlm How should I investigate it in WC source code?
This proves you right: https://github.com/php-stubs/generator/pull/18/files

**Comment by tlewap** [comment]
If someone need ugly solution ten you can use sed:
```
sed -i -e 's#final class WC_Cart_Totals#abstract class WC_Cart_Totals#' vendor/php-stubs/woocommerce-stubs/woocommerce-stubs.php
```

**Comment by szepeviktor** [comment]
> use sed:

Okay-okay! What about the next abstract problem in future WC releases? I'm not though enough to work more and more.

**Comment by tlewap** [comment]
I have no idea, its just temporary solution...
In our case we use PHPStan to accept PRs so without that, PRs fails

**Comment by szepeviktor** [comment]
> we use PHPStan to accept PRs

Please revert to the previous version of WC stubs.

**Comment by herndlm** [comment]
I didn't understand the root cause fully yet, but I think whenever we really execute our "stubs" we most likely should never remove "irrelevant" methods from them. I'd like to understand it first, but don't have time for that right now. anyway, maybe you can just generate the stubs with the "include-irrelevant-symbols" kind of config we added wherever you need it, e.g. wordpress and woocomerce at least?

**Comment by szepeviktor** [comment]
> don't have time for that right now

In this situation I can also come up with work-arounds.
The problem is: we don't remove abstract methods but they are getting removed.
🐞 I think I start debugging that `if` ...

**Comment by szepeviktor** [comment]
@herndlm That removed abstract method comes from a trait (`WC_Item_Totals`, it is used in `WC_Cart_Totals`). I think that is the cause. How to fix it?

**Comment by herndlm** [comment]
I'll check this and add a test case a bit later today or tomorrow morning the latest. I thought I did check already, but I'm not sure anymore, but don't get your hopes up too high. I hope that's it and the fix should be simple :)

**Comment by herndlm** [comment]
> If someone need ugly solution ten you can use sed:
> 
> ```
> sed -i -e 's#final class WC_Cart_Totals#abstract class WC_Cart_Totals#' vendor/php-stubs/woocommerce-stubs/woocommerce-stubs.php
> ```

this shows that it removes the protected method because the class is final. which makes sense for stubs IMO, since it's not accessible from the outside. we can keep protected methods also when classes are final, but then we can also keep private ones too I guess? I'd still suggest to turn that removal feature off for the wordpress stubs, because they are going to be executed.

we could also turn it off by default and only turn it explicitly on via config?

**Comment by szepeviktor** [comment]
I'm thinking about stopping repaying WC's tech debt.
